### ISSUE TITLE
No Samples in Factory ESX download

### ISSUE THREAD

**Issue by benirose** [skratchdot/open-electribe-editor#33]
I downloaded the ESX Factory Data zip and loaded it into Open Electribe Editior, but it doesn't seem to have any samples configured with it.

The ESXSD Factory Data does include samples, although I'm not sure they would all fit on the smart media card.

**Comment by skratchdot** [comment]
The program doesn't load in .zip files (it only recognizes .esx / .wav / .aif / .mp3 files).  You first need to open the .zip file and copy the .esx file somewhere.

Also, the ESXSD Factory Data will fit on most smart media cards (that I'm aware of).  Most smart media cards are in the GB range, and the maximum .esx file is ~27MB.

Hope that helps!

**Comment by benirose** [comment]
Thanks. Yes, I unzipped the file and opened the .ESX file in the editor. However, I didn't see any samples in the ESX Factory Data file. However, the SD version does have samples, so I will try that out (or just find new sample packs). Thanks.
